name: env
on: workflow_dispatch
env:
  APP_ENV: dev
jobs:
  dev:
    env:
      APP_ENV: test
    runs-on: ubuntu-latest
    steps:
      - name: use variables
        env:
         APP_ENV: uat
        run: echo $APP_ENV
